#!/bin/sh /etc/rc.common

#Place this file into /etc/init.d/modbus2mqtt! 

START=99
STOP=0
USE_PROCD=1

SCRIPT="/root/modbus_scripts/main.lua"

start_service() {
    procd_open_instance
    procd_set_param command "$SCRIPT"

    #procd_set_param stdout 1
    #procd_set_param stderr 1

    procd_set_param respawn 3600 15 0

    procd_close_instance
}

